In [1]:
import pandas as pd

bmi_input = [
    {"Gender": "Male", "HeightCm": 171, "WeightKg": 96},
    {"Gender": "Male", "HeightCm": 161, "WeightKg": 85},
    {"Gender": "Male", "HeightCm": 180, "WeightKg": 77},
    {"Gender": "Female", "HeightCm": 166, "WeightKg": 62},
    {"Gender": "Female", "HeightCm": 150, "WeightKg": 70},
    {"Gender": "Female", "HeightCm": 167, "WeightKg": 82}
]
bmi_input = bmi_input * 10000
bmi_table = [
    {"category": "Underweight", "range_min": 0, "range_max": 18.4, "risk": "Malnutrition risk"},
    {"category": "Normal weight", "range_min": 18.5, "range_max": 24.9, "risk": "Low risk"},
    {"category": "Overweight", "range_min": 25, "range_max": 29.9, "risk": "Enhanced risk"},
    {"category": "Moderately obese", "range_min": 30, "range_max": 34.9, "risk": "Medium risk"},
    {"category": "Severely obese", "range_min": 35, "range_max": 39.9, "risk": "High risk"},
    {"category": "Very severely obese", "range_min": 40, "range_max": 0, "risk": "Very high risk"},
]

In [3]:
# convert input to dataframe
bmi_table_df = pd.DataFrame(bmi_table)
bmi_table_df.head()

           category  range_min  range_max               risk
0       Underweight        0.0       18.4  Malnutrition risk
1     Normal weight       18.5       24.9           Low risk
2        Overweight       25.0       29.9      Enhanced risk
3  Moderately obese       30.0       34.9        Medium risk
4    Severely obese       35.0       39.9          High risk

In [6]:
class BMICalculator:
    def __init__(self, data):
        self.data = data
        self.result_index = 0
        self.result_list = []
        self.risk = None
        self.category = None
        
    def calculate_bmi(self):
        # Calcualte Given DataFrame BMI
        self.data["bmi"] = round(
            self.data['WeightKg'] / (self.data['HeightCm']/100) ** 2, 2)
        self.data["risk"] = self.data["bmi"].apply(self.get_risk)
        self.data["category"] = self.data["bmi"].apply(self.get_category)
        return self.data
    
    def get_risk(self, bmi):
        # Get BMI Risk value
        self.result_list = list(bmi_table_df['range_max'] >= bmi) & (bmi_table_df['range_min'] <= bmi)
        self.result_index = self.result_list[self.result_list == True]
        self.risk = bmi_table_df["risk"][self.result_index.index[0]]
        return str(self.risk)

    def get_category(self, bmi):
        # GET BMI Category Value
        self.result_list = list(bmi_table_df['range_max'] >= bmi) & (bmi_table_df['range_min'] <= bmi)
        self.result_index = self.result_list[self.result_list == True]
        self.category = bmi_table_df["category"][self.result_index.index[0]]
        return str(self.category)

In [7]:
b = BMICalculator(pd.DataFrame(bmi_input))
b.calculate_bmi()

       Gender  HeightCm  WeightKg    bmi           risk          category
0        Male       171        96  32.83    Medium risk  Moderately obese
1        Male       161        85  32.79    Medium risk  Moderately obese
2        Male       180        77  23.77       Low risk     Normal weight
3      Female       166        62  22.50       Low risk     Normal weight
4      Female       150        70  31.11    Medium risk  Moderately obese
...       ...       ...       ...    ...            ...               ...
59995    Male       161        85  32.79    Medium risk  Moderately obese
59996    Male       180        77  23.77       Low risk     Normal weight
59997  Female       166        62  22.50       Low risk     Normal weight
59998  Female       150        70  31.11    Medium risk  Moderately obese
59999  Female       167        82  29.40  Enhanced risk        Overweight

[60000 rows x 6 columns]

In [5]:
def get_risk(bmi):
    result_list = list(bmi_table_df['range_min'] >= bmi)
    result_index = result_list[result_list == True]
    risk = bmi_table_df["risk"][result_index.index[0]]
    return str(risk)

def get_category(bmi):
    result_index = list(bmi_table_df['range_max'] >= bmi) & (bmi_table_df['range_min'] <= bmi)[result_list == True]
    risk = bmi_table_df["category"][result_index.index[0]]
    return str(risk)

In [6]:
bmi_df['risk'] = bmi_df['bmi'].apply(get_risk)

[False, False, False, False, True, True]

AttributeError: 'bool' object has no attribute 'index'

In [8]:
# bmi_df["risk"] = bmi_df.apply(lambda x: ( bmi_df['WeightKg'] / (bmi_df['HeightCm']/100) ** 2), axis=1)
bmi_df["bmi"] = round(bmi_df['WeightKg'] / (bmi_df['HeightCm']/100) ** 2, 2)
bmi_df.head()

   Gender  HeightCm  WeightKg    bmi
0    Male       171        96  32.83
1    Male       161        85  32.79
2    Male       180        77  23.77
3  Female       166        62  22.50
4  Female       150        70  31.11

In [10]:
def get_risk(bmi):
    result_list = list(bmi_table_df['range_min'] >= bmi)
    print(result_list)
    result_index = result_list[result_list == True]
    risk = bmi_table_df["risk"][result_index.index[0]]
    return str(risk)

def get_category(bmi):
    result_index = list(bmi_table_df['range_max'] >= bmi) & (bmi_table_df['range_min'] <= bmi)[result_list == True]
    risk = bmi_table_df["category"][result_index.index[0]]
    return str(risk)

In [11]:
#bmi_df["risk"] = 
#bmi_df["category"] = bmi_df["bmi"].apply(get_category)
bmi_df['risk'] = bmi_df['bmi'].apply(get_risk)

[False, False, False, False, True, True]

AttributeError: 'bool' object has no attribute 'index'

In [15]:
bmi_df.head()

   Gender  HeightCm  WeightKg    bmi         risk
0    Male       171        96  32.83  Medium risk
1    Male       161        85  32.79  Medium risk
2    Male       180        77  23.77     Low risk
3  Female       166        62  22.50     Low risk
4  Female       150        70  31.11  Medium risk